### ISSUE TITLE
Can't build  

### ISSUE THREAD

**Issue by islam3zzat** [jossmac/react-images#138]
**Steps to reproduce the behavior:**
after cloning 
I run 
npm install
then 
npm run build
the I get this error at this task build:example:scripts
[13:50:38] Starting 'build:example:scripts'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
ReferenceError: [BABEL] $HOME/projects/react-images/src/Lightbox.js: Unknown option: $HOME/.babelrc.presets
    at Logger.error ($HOME/projects/react-images/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions $HOME/projects/react-images/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)

**Comment by islam3zzat** [comment]
I had some issue in my env, its working now
